files:
  option/create: resources/views/components/ui/combobox/option/create.blade.php
  option/empty: resources/views/components/ui/combobox/option/empty.blade.php
  pillbox-trigger: resources/views/components/ui/combobox/pillbox-trigger.blade.php
  group: resources/views/components/ui/combobox/group.blade.php
  index: resources/views/components/ui/combobox/index.blade.php
  loading: resources/views/components/ui/combobox/loading.blade.php
  option: resources/views/components/ui/combobox/option.blade.php
  options: resources/views/components/ui/combobox/options.blade.php
  search: resources/views/components/ui/combobox/search.blade.php
  combobox: resources/js/components/combobox.js
  separator: resources/views/components/ui/separator.blade.php
  trigger: resources/views/components/ui/trigger.blade.php
dependencies:
  internal: [icon,text]
